import type { JobPost } from '@/types'
import { IndexedDBRepository } from '@/libs/storage/repository'

const jobpost: JobPost[] = [
  {
    id: 'job-001',
    title: 'Senior Frontend Developer',
    description: 'Kami mencari pengembang Frontend berpengalaman untuk membangun antarmuka web yang responsif dan performan.',
    requirements: ['Minimal 5 tahun pengalaman React/Next.js', 'Keahlian dalam Tailwind CSS dan TypeScript', 'Memahami State Management seperti Redux atau Zustand'],
    responsibilities: ['Mengembangkan fitur baru menggunakan React', 'Melakukan code review', 'Optimasi performa aplikasi web'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Selatan, DKI Jakarta',
    minSalary: 18_000_000,
    maxSalary: 25_000_000,
    createdAt: '2025-12-27T10:43:26.509Z',
    updatedAt: '2025-12-27T10:43:26.509Z',
  },
  {
    id: 'job-002',
    title: 'Backend Engineer (Go)',
    description: 'Membangun sistem backend yang scalable dan maintainable menggunakan bahasa pemrograman Go.',
    requirements: ['Pengalaman dengan Golang minimal 3 tahun', 'Paham arsitektur Microservices', 'Terbiasa dengan PostgreSQL dan Redis'],
    responsibilities: ['Merancang dan mengimplementasikan API', 'Maintenance database', 'Integrasi layanan pihak ketiga'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Bandung, Jawa Barat',
    minSalary: 15_000_000,
    maxSalary: 22_000_000,
    createdAt: '2025-12-27T11:00:00.000Z',
    updatedAt: '2025-12-27T11:00:00.000Z',
  },
  {
    id: 'job-003',
    title: 'UI/UX Designer',
    description: 'Menciptakan pengalaman pengguna yang intuitif dan desain visual yang menarik untuk produk digital kami.',
    requirements: ['Mahir menggunakan Figma', 'Memiliki portfolio desain produk yang kuat', 'Memahami prinsip User-Centered Design'],
    responsibilities: ['Membuat wireframe dan prototype', 'Melakukan user research', 'Kolaborasi dengan tim produk dan dev'],
    department: 'Product',
    employmentType: 'full-time',
    status: 'published',
    location: 'Kediri, Jawa Timur',
    minSalary: 8_000_000,
    maxSalary: 12_000_000,
    createdAt: '2025-12-27T09:30:00.000Z',
    updatedAt: '2025-12-27T09:30:00.000Z',
  },
  {
    id: 'job-004',
    title: 'Digital Marketing Specialist',
    description: 'Mengelola kampanye iklan digital dan meningkatkan brand awareness melalui berbagai channel.',
    requirements: ['Pengalaman mengelola Google Ads & FB Ads', 'Kemampuan analisis data menggunakan GA4', 'Paham SEO/SEM'],
    responsibilities: ['Membuat strategi kampanye bulanan', 'Analisis performa iklan', 'Manajemen budget marketing'],
    department: 'Marketing',
    employmentType: 'full-time',
    status: 'draft',
    location: 'Surabaya, Jawa Timur',
    minSalary: 7_000_000,
    maxSalary: 11_000_000,
    createdAt: '2025-12-26T08:00:00.000Z',
    updatedAt: '2025-12-26T08:00:00.000Z',
  },
  {
    id: 'job-005',
    title: 'HR Generalist',
    description: 'Mengelola proses rekrutmen, administrasi karyawan, dan pengembangan SDM.',
    requirements: ['Lulusan Psikologi atau Hukum', 'Memahami UU Ketenagakerjaan', 'Komunikasi interpersonal yang baik'],
    responsibilities: ['Proses end-to-end recruitment', 'Payroll administration', 'Employee engagement program'],
    department: 'Human Resources',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Pusat, DKI Jakarta',
    minSalary: 9_000_000,
    maxSalary: 13_000_000,
    createdAt: '2025-12-25T14:20:00.000Z',
    updatedAt: '2025-12-25T14:20:00.000Z',
  },
  {
    id: 'job-006',
    title: 'Data Analyst',
    description: 'Menganalisis data besar untuk memberikan wawasan bisnis yang dapat ditindaklanjuti.',
    requirements: ['Mahir SQL dan Python/R', 'Pengalaman dengan Tableau atau Power BI', 'Kuat dalam statistik'],
    responsibilities: ['Cleaning data', 'Membuat dashboard visualisasi', 'Presentasi temuan kepada stakeholder'],
    department: 'Data',
    employmentType: 'full-time',
    status: 'published',
    location: 'Tangerang, Banten',
    minSalary: 12_000_000,
    maxSalary: 18_000_000,
    createdAt: '2025-12-24T10:00:00.000Z',
    updatedAt: '2025-12-24T10:00:00.000Z',
  },
  {
    id: 'job-007',
    title: 'Customer Success Manager',
    description: 'Memastikan kepuasan pelanggan dan retensi jangka panjang.',
    requirements: ['Pengalaman minimal 2 tahun di bidang CS/Account Management', 'Kemampuan problem-solving', 'Sabar dan komunikatif'],
    responsibilities: ['Menangani keluhan klien besar', 'Onboarding klien baru', 'Upselling produk'],
    department: 'Customer Service',
    employmentType: 'full-time',
    status: 'published',
    location: 'Kediri, Jawa Timur',
    minSalary: 6_000_000,
    maxSalary: 9_500_000,
    createdAt: '2025-12-23T11:15:00.000Z',
    updatedAt: '2025-12-23T11:15:00.000Z',
  },
  {
    id: 'job-008',
    title: 'Mobile App Developer (Flutter)',
    description: 'Membangun aplikasi mobile cross-platform menggunakan Flutter.',
    requirements: ['Pengalaman Flutter & Dart minimal 2 tahun', 'Paham arsitektur BLoC atau Provider', 'Pernah deploy ke PlayStore/AppStore'],
    responsibilities: ['Coding fitur mobile app', 'Bug fixing', 'Optimasi performa mobile'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Yogyakarta, DIY',
    minSalary: 10_000_000,
    maxSalary: 16_000_000,
    createdAt: '2025-12-22T09:00:00.000Z',
    updatedAt: '2025-12-22T09:00:00.000Z',
  },
  {
    id: 'job-009',
    title: 'Finance & Accounting',
    description: 'Mengelola laporan keuangan harian dan pajak perusahaan.',
    requirements: ['Minimal S1 Akuntansi', 'Memiliki sertifikat Brevet A/B diutamakan', 'Mahir Excel'],
    responsibilities: ['Menyusun laporan laba rugi', 'Rekonsiliasi bank', 'Pelaporan pajak bulanan'],
    department: 'Finance',
    employmentType: 'full-time',
    status: 'published',
    location: 'Malang, Jawa Timur',
    minSalary: 5_500_000,
    maxSalary: 8_500_000,
    createdAt: '2025-12-21T15:45:00.000Z',
    updatedAt: '2025-12-21T15:45:00.000Z',
  },
  {
    id: 'job-010',
    title: 'DevOps Engineer',
    description: 'Mengelola infrastruktur cloud dan pipeline CI/CD.',
    requirements: ['Pengalaman dengan AWS/GCP', 'Paham Docker dan Kubernetes', 'Skill scripting (Bash/Python)'],
    responsibilities: ['Automasi deployment', 'Monitoring server', 'Keamanan infrastruktur'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Barat, DKI Jakarta',
    minSalary: 16_000_000,
    maxSalary: 24_000_000,
    createdAt: '2025-12-20T10:30:00.000Z',
    updatedAt: '2025-12-20T10:30:00.000Z',
  },
  {
    id: 'job-011',
    title: 'Copywriter',
    description: 'Membuat narasi menarik untuk materi promosi dan konten media sosial.',
    requirements: ['Kreatif dan up-to-date dengan tren', 'Mampu menulis dalam Bahasa Indonesia yang baku maupun santai', 'Portfolio tulisan'],
    responsibilities: ['Menulis script iklan', 'Caption media sosial', 'Content plan bulanan'],
    department: 'Marketing',
    employmentType: 'contract',
    status: 'published',
    location: 'Remote',
    minSalary: 5_000_000,
    maxSalary: 8_000_000,
    createdAt: '2025-12-19T13:00:00.000Z',
    updatedAt: '2025-12-19T13:00:00.000Z',
  },
  {
    id: 'job-012',
    title: 'Product Manager',
    description: 'Menjembatani visi bisnis dengan pengembangan produk teknis.',
    requirements: ['Pengalaman minimal 3 tahun sebagai PM', 'Analytical thinking yang kuat', 'Skill manajemen proyek'],
    responsibilities: ['Membuat product roadmap', 'Prioritas backlog fitur', 'Koordinasi antar tim'],
    department: 'Product',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Selatan, DKI Jakarta',
    minSalary: 20_000_000,
    maxSalary: 35_000_000,
    createdAt: '2025-12-18T11:00:00.000Z',
    updatedAt: '2025-12-18T11:00:00.000Z',
  },
  {
    id: 'job-013',
    title: 'Sales Executive',
    description: 'Mencari lead baru dan melakukan negosiasi penjualan B2B.',
    requirements: ['Target oriented', 'Memiliki jaringan luas', 'Skill negosiasi yang baik'],
    responsibilities: ['Cold calling', 'Meeting dengan klien potensial', 'Mencapai target sales'],
    department: 'Sales',
    employmentType: 'full-time',
    status: 'published',
    location: 'Surabaya, Jawa Timur',
    minSalary: 5_000_000,
    maxSalary: 15_000_000,
    createdAt: '2025-12-17T09:20:00.000Z',
    updatedAt: '2025-12-17T09:20:00.000Z',
  },
  {
    id: 'job-014',
    title: 'QA Automation Engineer',
    description: 'Menjamin kualitas software melalui pengujian otomatis.',
    requirements: ['Paham Selenium/Cypress', 'Pengalaman testing API', 'Paham SDLC'],
    responsibilities: ['Membuat script automation test', 'Manual testing jika diperlukan', 'Pelaporan bug secara detail'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Tangerang Selatan, Banten',
    minSalary: 11_000_000,
    maxSalary: 17_000_000,
    createdAt: '2025-12-16T10:00:00.000Z',
    updatedAt: '2025-12-16T10:00:00.000Z',
  },
  {
    id: 'job-015',
    title: 'Legal Counsel',
    description: 'Menangani masalah hukum perusahaan dan peninjauan kontrak.',
    requirements: ['Lulusan Hukum (SH)', 'Memiliki lisensi advokat (PERADI) diutamakan', 'Detail oriented'],
    responsibilities: ['Review kontrak kerjasama', 'Kepatuhan regulasi', 'Legal drafting'],
    department: 'Legal',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Timur, DKI Jakarta',
    minSalary: 12_000_000,
    maxSalary: 18_000_000,
    createdAt: '2025-12-15T14:00:00.000Z',
    updatedAt: '2025-12-15T14:00:00.000Z',
  },
  {
    id: 'job-016',
    title: 'Social Media Manager',
    description: 'Mengelola komunitas dan pertumbuhan di platform sosial media.',
    requirements: ['Kreatif', 'Paham algoritma Instagram/TikTok', 'Skill editing video dasar'],
    responsibilities: ['Posting harian', 'Interaksi dengan followers', 'Analisis tren konten'],
    department: 'Marketing',
    employmentType: 'full-time',
    status: 'published',
    location: 'Kediri, Jawa Timur',
    minSalary: 4_500_000,
    maxSalary: 7_000_000,
    createdAt: '2025-12-14T10:43:26.509Z',
    updatedAt: '2025-12-14T10:43:26.509Z',
  },
  {
    id: 'job-017',
    title: 'AI/Machine Learning Engineer',
    description: 'Mengembangkan model ML untuk fitur rekomendasi produk.',
    requirements: ['Kuat di Matematika/Statistik', 'Mahir Python & PyTorch/TensorFlow', 'Paham NLP'],
    responsibilities: ['Pelatihan model ML', 'Optimasi akurasi model', 'Deployment model ke produksi'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Selatan, DKI Jakarta',
    minSalary: 25_000_000,
    maxSalary: 40_000_000,
    createdAt: '2025-12-13T09:00:00.000Z',
    updatedAt: '2025-12-13T09:00:00.000Z',
  },
  {
    id: 'job-018',
    title: 'Graphic Designer',
    description: 'Membuat aset visual untuk kebutuhan marketing dan brand.',
    requirements: ['Mahir Adobe Illustrator & Photoshop', 'Kreatif', 'Mampu bekerja dalam deadline'],
    responsibilities: ['Desain banner iklan', 'Desain konten sosmed', 'Branding identity'],
    department: 'Creative',
    employmentType: 'full-time',
    status: 'published',
    location: 'Yogyakarta, DIY',
    minSalary: 4_000_000,
    maxSalary: 6_500_000,
    createdAt: '2025-12-12T11:30:00.000Z',
    updatedAt: '2025-12-12T11:30:00.000Z',
  },
  {
    id: 'job-019',
    title: 'Security Engineer',
    description: 'Menjaga keamanan sistem informasi perusahaan dari serangan siber.',
    requirements: ['Paham penetration testing', 'Sertifikasi CEH/CompTIA Security+', 'Analisis kerentanan'],
    responsibilities: ['Audit keamanan berkala', 'Incident response', 'Keamanan jaringan'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Pusat, DKI Jakarta',
    minSalary: 18_000_000,
    maxSalary: 28_000_000,
    createdAt: '2025-12-11T15:00:00.000Z',
    updatedAt: '2025-12-11T15:00:00.000Z',
  },
  {
    id: 'job-020',
    title: 'Content Creator',
    description: 'Membuat konten video pendek untuk TikTok dan Reels.',
    requirements: ['Percaya diri di depan kamera', 'Skill storytelling', 'Up-to-date trend'],
    responsibilities: ['Take video', 'Editing video pendek', 'Mencari ide konten'],
    department: 'Marketing',
    employmentType: 'contract',
    status: 'published',
    location: 'Remote',
    minSalary: 4_000_000,
    maxSalary: 7_500_000,
    createdAt: '2025-12-10T10:00:00.000Z',
    updatedAt: '2025-12-10T10:00:00.000Z',
  },
  {
    id: 'job-021',
    title: 'IT Support',
    description: 'Membantu operasional teknis kantor dan maintenance perangkat.',
    requirements: ['Paham jaringan (Mikrotik)', 'Troubleshooting hardware/software', 'Komunikatif'],
    responsibilities: ['Setting laptop karyawan baru', 'Maintenance server kantor', 'Helpdesk internal'],
    department: 'Information Technology',
    employmentType: 'full-time',
    status: 'published',
    location: 'Semarang, Jawa Tengah',
    minSalary: 4_500_000,
    maxSalary: 6_000_000,
    createdAt: '2025-12-09T08:30:00.000Z',
    updatedAt: '2025-12-09T08:30:00.000Z',
  },
  {
    id: 'job-022',
    title: 'Business Development',
    description: 'Mengidentifikasi peluang bisnis baru dan kemitraan strategis.',
    requirements: ['Skill presentasi yang baik', 'Analisis pasar', 'Networking'],
    responsibilities: ['Mencari partner bisnis', 'Drafting proposal kerjasama', 'Riset kompetitor'],
    department: 'Sales',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Selatan, DKI Jakarta',
    minSalary: 10_000_000,
    maxSalary: 15_000_000,
    createdAt: '2025-12-08T11:00:00.000Z',
    updatedAt: '2025-12-08T11:00:00.000Z',
  },
  {
    id: 'job-023',
    title: 'Warehouse Supervisor',
    description: 'Mengawasi operasional gudang dan manajemen stok.',
    requirements: ['Pengalaman di logistik minimal 3 tahun', 'Tegas dan teliti', 'Bisa menggunakan sistem WMS'],
    responsibilities: ['Kontrol stok barang', 'Manajemen kurir', 'Laporan inventory bulanan'],
    department: 'Operations',
    employmentType: 'full-time',
    status: 'published',
    location: 'Kediri, Jawa Timur',
    minSalary: 6_000_000,
    maxSalary: 8_500_000,
    createdAt: '2025-12-07T09:00:00.000Z',
    updatedAt: '2025-12-07T09:00:00.000Z',
  },
  {
    id: 'job-024',
    title: 'Fullstack Developer (Node.js & React)',
    description: 'Membangun aplikasi end-to-end dari frontend hingga backend.',
    requirements: ['Mahir JavaScript/TypeScript', 'Pengalaman dengan Express/NestJS', 'Paham arsitektur database'],
    responsibilities: ['Ngoding fitur fullstack', 'Integrasi API', 'Unit testing'],
    department: 'Engineering',
    employmentType: 'full-time',
    status: 'published',
    location: 'Denpasar, Bali',
    minSalary: 12_000_000,
    maxSalary: 20_000_000,
    createdAt: '2025-12-06T14:20:00.000Z',
    updatedAt: '2025-12-06T14:20:00.000Z',
  },
  {
    id: 'job-025',
    title: 'Office Administrator',
    description: 'Mengelola urusan administrasi dan operasional kantor harian.',
    requirements: ['Mahir Ms. Office', 'Rapi dan terorganisir', 'Multitasking'],
    responsibilities: ['Pengarsipan dokumen', 'Pemesanan supply kantor', 'Mengatur jadwal meeting'],
    department: 'General Affair',
    employmentType: 'full-time',
    status: 'published',
    location: 'Surabaya, Jawa Timur',
    minSalary: 4_200_000,
    maxSalary: 5_500_000,
    createdAt: '2025-12-05T10:00:00.000Z',
    updatedAt: '2025-12-05T10:00:00.000Z',
  },
  {
    id: 'job-026',
    title: 'Project Manager (Construction)',
    description: 'Mengawasi proyek pembangunan dari awal hingga selesai.',
    requirements: ['S1 Teknik Sipil', 'Pengalaman manajemen proyek fisik', 'Tegas dalam pengawasan lapangan'],
    responsibilities: ['Budgeting proyek', 'Koordinasi kontraktor', 'Monitoring timeline pembangunan'],
    department: 'Project',
    employmentType: 'full-time',
    status: 'published',
    location: 'Kediri, Jawa Timur',
    minSalary: 15_000_000,
    maxSalary: 25_000_000,
    createdAt: '2025-12-04T08:00:00.000Z',
    updatedAt: '2025-12-04T08:00:00.000Z',
  },
  {
    id: 'job-027',
    title: 'Customer Service Representative',
    description: 'Melayani pertanyaan dan keluhan pelanggan melalui chat dan telepon.',
    requirements: ['Komunikasi lancar', 'Sabar', 'Bisa mengetik cepat'],
    responsibilities: ['Menjawab chat pelanggan', 'Input keluhan ke sistem', 'Follow up tiket'],
    department: 'Customer Service',
    employmentType: 'full-time',
    status: 'published',
    location: 'Malang, Jawa Timur',
    minSalary: 3_800_000,
    maxSalary: 5_000_000,
    createdAt: '2025-12-03T11:00:00.000Z',
    updatedAt: '2025-12-03T11:00:00.000Z',
  },
  {
    id: 'job-028',
    title: 'Tax Specialist',
    description: 'Mengelola perpajakan perusahaan agar sesuai regulasi terbaru.',
    requirements: ['Brevet A & B', 'Pengalaman 3 tahun di bidang pajak', 'Paham e-Faktur'],
    responsibilities: ['Perhitungan PPh dan PPN', 'Pelaporan SPT Tahunan', 'Audit pajak internal'],
    department: 'Finance',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Barat, DKI Jakarta',
    minSalary: 10_000_000,
    maxSalary: 15_000_000,
    createdAt: '2025-12-02T13:45:00.000Z',
    updatedAt: '2025-12-02T13:45:00.000Z',
  },
  {
    id: 'job-029',
    title: 'Video Editor',
    description: 'Mengedit video konten YouTube dan iklan komersial.',
    requirements: ['Mahir Adobe Premiere Pro/Final Cut', 'Paham color grading', 'Audio mixing dasar'],
    responsibilities: ['Editing video mentah', 'Menambahkan motion graphic', 'Final rendering'],
    department: 'Creative',
    employmentType: 'full-time',
    status: 'published',
    location: 'Bandung, Jawa Barat',
    minSalary: 6_000_000,
    maxSalary: 10_000_000,
    createdAt: '2025-12-01T10:00:00.000Z',
    updatedAt: '2025-12-01T10:00:00.000Z',
  },
  {
    id: 'job-030',
    title: 'Product Researcher',
    description: 'Melakukan riset pasar untuk pengembangan produk baru.',
    requirements: ['Pengalaman kualitatif & kuantitatif research', 'Critical thinking', 'Sosiologi/Psikologi background'],
    responsibilities: ['User interview', 'Analisis kompetitor', 'Penyusunan laporan riset'],
    department: 'Product',
    employmentType: 'full-time',
    status: 'published',
    location: 'Jakarta Selatan, DKI Jakarta',
    minSalary: 11_000_000,
    maxSalary: 17_000_000,
    createdAt: '2025-11-30T09:00:00.000Z',
    updatedAt: '2025-11-30T09:00:00.000Z',
  },
]

export class JobPostRepository extends IndexedDBRepository<JobPost> {
  constructor () {
    super('jobpost-db', 'jobpost')
    this.init()
  }

  async init () {
    if (await this.isEmpty()) {
      this.create(jobpost)
    }
  }
}
