/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/ui/app-footer.vue')['default']
    Breadcrumbs: typeof import('./components/ui/breadcrumbs.vue')['default']
    ComponentTitle: typeof import('./components/ui/component-title.vue')['default']
    Footer: typeof import('./components/layouts/dashboard/footer.vue')['default']
    Header: typeof import('./components/layouts/dashboard/header/header.vue')['default']
    HelloWorld: typeof import('./components/ui/hello-world.vue')['default']
    InputArrayObject: typeof import('./components/ui/input-array-object.vue')['default']
    InputArrayString: typeof import('./components/ui/input-array-string.vue')['default']
    Logo: typeof import('./components/layouts/dashboard/logo.vue')['default']
    NavCollapse: typeof import('./components/layouts/dashboard/sidebar/nav-collapse.vue')['default']
    NavGroup: typeof import('./components/layouts/dashboard/sidebar/nav-group.vue')['default']
    NavItem: typeof import('./components/layouts/dashboard/sidebar/nav-item.vue')['default']
    Notification: typeof import('./components/ui/notification.vue')['default']
    NotificationDd: typeof import('./components/layouts/dashboard/header/notification-dd.vue')['default']
    Page: typeof import('./components/layouts/dashboard/page.vue')['default']
    ProfileDd: typeof import('./components/layouts/dashboard/header/profile-dd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBarPanel: typeof import('./components/layouts/dashboard/header/search-bar-panel.vue')['default']
    Sidebar: typeof import('./components/layouts/dashboard/sidebar/sidebar.vue')['default']
    ThemeSwitcher: typeof import('./components/ui/theme-switcher.vue')['default']
    TreeDataTable: typeof import('./components/fragments/table/tree-data-table.vue')['default']
    UiParentCard: typeof import('./components/ui/ui-parent-card.vue')['default']
    UiTitleCard: typeof import('./components/ui/ui-title-card.vue')['default']
  }
}

// For TSX support
declare global {
  const AppFooter: typeof import('./components/ui/app-footer.vue')['default']
  const Breadcrumbs: typeof import('./components/ui/breadcrumbs.vue')['default']
  const ComponentTitle: typeof import('./components/ui/component-title.vue')['default']
  const Footer: typeof import('./components/layouts/dashboard/footer.vue')['default']
  const Header: typeof import('./components/layouts/dashboard/header/header.vue')['default']
  const HelloWorld: typeof import('./components/ui/hello-world.vue')['default']
  const InputArrayObject: typeof import('./components/ui/input-array-object.vue')['default']
  const InputArrayString: typeof import('./components/ui/input-array-string.vue')['default']
  const Logo: typeof import('./components/layouts/dashboard/logo.vue')['default']
  const NavCollapse: typeof import('./components/layouts/dashboard/sidebar/nav-collapse.vue')['default']
  const NavGroup: typeof import('./components/layouts/dashboard/sidebar/nav-group.vue')['default']
  const NavItem: typeof import('./components/layouts/dashboard/sidebar/nav-item.vue')['default']
  const Notification: typeof import('./components/ui/notification.vue')['default']
  const NotificationDd: typeof import('./components/layouts/dashboard/header/notification-dd.vue')['default']
  const Page: typeof import('./components/layouts/dashboard/page.vue')['default']
  const ProfileDd: typeof import('./components/layouts/dashboard/header/profile-dd.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchBarPanel: typeof import('./components/layouts/dashboard/header/search-bar-panel.vue')['default']
  const Sidebar: typeof import('./components/layouts/dashboard/sidebar/sidebar.vue')['default']
  const ThemeSwitcher: typeof import('./components/ui/theme-switcher.vue')['default']
  const TreeDataTable: typeof import('./components/fragments/table/tree-data-table.vue')['default']
  const UiParentCard: typeof import('./components/ui/ui-parent-card.vue')['default']
  const UiTitleCard: typeof import('./components/ui/ui-title-card.vue')['default']
}