/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/_components/AuthFooter': RouteRecordInfo<'/auth/_components/AuthFooter', '/auth/_components/AuthFooter', Record<never, never>, Record<never, never>>,
    '/auth/_components/form/form-login': RouteRecordInfo<'/auth/_components/form/form-login', '/auth/_components/form/form-login', Record<never, never>, Record<never, never>>,
    '/auth/_components/form/FormRegister': RouteRecordInfo<'/auth/_components/form/FormRegister', '/auth/_components/form/FormRegister', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/candidate/': RouteRecordInfo<'/candidate/', '/candidate', Record<never, never>, Record<never, never>>,
    '/candidate/_components/form/form-candidate': RouteRecordInfo<'/candidate/_components/form/form-candidate', '/candidate/_components/form/form-candidate', Record<never, never>, Record<never, never>>,
    '/candidate/_components/table-candidate': RouteRecordInfo<'/candidate/_components/table-candidate', '/candidate/_components/table-candidate', Record<never, never>, Record<never, never>>,
    '/candidate/[id]/': RouteRecordInfo<'/candidate/[id]/', '/candidate/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/candidate/[id]/update/': RouteRecordInfo<'/candidate/[id]/update/', '/candidate/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/candidate/create/': RouteRecordInfo<'/candidate/create/', '/candidate/create', Record<never, never>, Record<never, never>>,
    '/cv/': RouteRecordInfo<'/cv/', '/cv', Record<never, never>, Record<never, never>>,
    '/cv/_components/form/form-cv': RouteRecordInfo<'/cv/_components/form/form-cv', '/cv/_components/form/form-cv', Record<never, never>, Record<never, never>>,
    '/cv/_components/table-cv': RouteRecordInfo<'/cv/_components/table-cv', '/cv/_components/table-cv', Record<never, never>, Record<never, never>>,
    '/cv/[id]/': RouteRecordInfo<'/cv/[id]/', '/cv/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cv/[id]/update/': RouteRecordInfo<'/cv/[id]/update/', '/cv/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cv/create/': RouteRecordInfo<'/cv/create/', '/cv/create', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/analytics-report': RouteRecordInfo<'/dashboard/_components/analytics-report', '/dashboard/_components/analytics-report', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/help-support': RouteRecordInfo<'/dashboard/_components/help-support', '/dashboard/_components/help-support', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/income-overview': RouteRecordInfo<'/dashboard/_components/income-overview', '/dashboard/_components/income-overview', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/recent-order': RouteRecordInfo<'/dashboard/_components/recent-order', '/dashboard/_components/recent-order', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/sales-report': RouteRecordInfo<'/dashboard/_components/sales-report', '/dashboard/_components/sales-report', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/transaction-history': RouteRecordInfo<'/dashboard/_components/transaction-history', '/dashboard/_components/transaction-history', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/unique-visitor': RouteRecordInfo<'/dashboard/_components/unique-visitor', '/dashboard/_components/unique-visitor', Record<never, never>, Record<never, never>>,
    '/dashboard/_components/widget-five': RouteRecordInfo<'/dashboard/_components/widget-five', '/dashboard/_components/widget-five', Record<never, never>, Record<never, never>>,
    '/job-post/': RouteRecordInfo<'/job-post/', '/job-post', Record<never, never>, Record<never, never>>,
    '/job-post/_components/form/form-job-post': RouteRecordInfo<'/job-post/_components/form/form-job-post', '/job-post/_components/form/form-job-post', Record<never, never>, Record<never, never>>,
    '/job-post/_components/table-job-post': RouteRecordInfo<'/job-post/_components/table-job-post', '/job-post/_components/table-job-post', Record<never, never>, Record<never, never>>,
    '/job-post/[id]/': RouteRecordInfo<'/job-post/[id]/', '/job-post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/job-post/[id]/update/': RouteRecordInfo<'/job-post/[id]/update/', '/job-post/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/job-post/create/': RouteRecordInfo<'/job-post/create/', '/job-post/create', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/_components/AuthFooter.vue': {
      routes: '/auth/_components/AuthFooter'
      views: never
    }
    'src/pages/auth/_components/form/form-login.vue': {
      routes: '/auth/_components/form/form-login'
      views: never
    }
    'src/pages/auth/_components/form/FormRegister.vue': {
      routes: '/auth/_components/form/FormRegister'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/pages/candidate/index.vue': {
      routes: '/candidate/'
      views: never
    }
    'src/pages/candidate/_components/form/form-candidate.vue': {
      routes: '/candidate/_components/form/form-candidate'
      views: never
    }
    'src/pages/candidate/_components/table-candidate.vue': {
      routes: '/candidate/_components/table-candidate'
      views: never
    }
    'src/pages/candidate/[id]/index.vue': {
      routes: '/candidate/[id]/'
      views: never
    }
    'src/pages/candidate/[id]/update/index.vue': {
      routes: '/candidate/[id]/update/'
      views: never
    }
    'src/pages/candidate/create/index.vue': {
      routes: '/candidate/create/'
      views: never
    }
    'src/pages/cv/index.vue': {
      routes: '/cv/'
      views: never
    }
    'src/pages/cv/_components/form/form-cv.vue': {
      routes: '/cv/_components/form/form-cv'
      views: never
    }
    'src/pages/cv/_components/table-cv.vue': {
      routes: '/cv/_components/table-cv'
      views: never
    }
    'src/pages/cv/[id]/index.vue': {
      routes: '/cv/[id]/'
      views: never
    }
    'src/pages/cv/[id]/update/index.vue': {
      routes: '/cv/[id]/update/'
      views: never
    }
    'src/pages/cv/create/index.vue': {
      routes: '/cv/create/'
      views: never
    }
    'src/pages/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/dashboard/_components/analytics-report.vue': {
      routes: '/dashboard/_components/analytics-report'
      views: never
    }
    'src/pages/dashboard/_components/help-support.vue': {
      routes: '/dashboard/_components/help-support'
      views: never
    }
    'src/pages/dashboard/_components/income-overview.vue': {
      routes: '/dashboard/_components/income-overview'
      views: never
    }
    'src/pages/dashboard/_components/recent-order.vue': {
      routes: '/dashboard/_components/recent-order'
      views: never
    }
    'src/pages/dashboard/_components/sales-report.vue': {
      routes: '/dashboard/_components/sales-report'
      views: never
    }
    'src/pages/dashboard/_components/transaction-history.vue': {
      routes: '/dashboard/_components/transaction-history'
      views: never
    }
    'src/pages/dashboard/_components/unique-visitor.vue': {
      routes: '/dashboard/_components/unique-visitor'
      views: never
    }
    'src/pages/dashboard/_components/widget-five.vue': {
      routes: '/dashboard/_components/widget-five'
      views: never
    }
    'src/pages/job-post/index.vue': {
      routes: '/job-post/'
      views: never
    }
    'src/pages/job-post/_components/form/form-job-post.vue': {
      routes: '/job-post/_components/form/form-job-post'
      views: never
    }
    'src/pages/job-post/_components/table-job-post.vue': {
      routes: '/job-post/_components/table-job-post'
      views: never
    }
    'src/pages/job-post/[id]/index.vue': {
      routes: '/job-post/[id]/'
      views: never
    }
    'src/pages/job-post/[id]/update/index.vue': {
      routes: '/job-post/[id]/update/'
      views: never
    }
    'src/pages/job-post/create/index.vue': {
      routes: '/job-post/create/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
