export const PERMISSION = {
  ADMIN: {
    user_read: 'admin.user.read',
    user_write: 'admin.user.write',
    user_update: 'admin.user.update',
    user_delete: 'admin.user.delete',
    cv_read: 'admin.cv.read',
    cv_write: 'admin.cv.write',
    cv_update: 'admin.cv.update',
    cv_delete: 'admin.cv.delete',
    candidate_read: 'admin.candidate.read',
    candidate_write: 'admin.candidate.write',
    candidate_update: 'admin.candidate.update',
    candidate_delete: 'admin.candidate.delete',
    job_read: 'admin.job-post.read',
    job_write: 'admin.job-post.write',
    job_update: 'admin.job-post.update',
    job_delete: 'admin.job-post.delete',
  },
  CANDIDATE: {
    cv_read: 'candidate.cv.read',
    cv_write: 'candidate.cv.write',
    cv_update: 'candidate.cv.update',
    cv_delete: 'candidate.cv.delete',
  },
}
